nano Dockerfile

FROM ubuntu:22.04

ENV FRONTEND=nonintercative

RUN apt update && \
        apt upgrade -y && apt install apache2 -y && \
        apt clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY index.html /var/www/html/
RUN chown -R www-data:www-data /var/www/html/
EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
